"""
Merge review sentiment signals into the model feature set.

Reads outputs/reviews_with_sentiment.csv (generated by script 15) and
joins monthly sentiment aggregates onto data/final/hotel_daily_master.csv.

Output: data/final/hotel_daily_master.csv  (updated in-place with new columns)

New columns added:
  review_sentiment_30d   — rolling 30-day mean sentiment from review publish dates
  review_volume_30d      — rolling 30-day review count (proxy for attention/buzz)
  complaint_flag         — 1 if a negative review (sentiment < -0.1) appeared in window
"""

import sys
import pandas as pd
import numpy as np
from pathlib import Path

BASE_DIR     = Path(__file__).resolve().parents[1]
OUTPUTS_DIR  = BASE_DIR / "outputs"
FINAL_DIR    = BASE_DIR / "data" / "final"

REVIEWS_CSV  = OUTPUTS_DIR / "reviews_with_sentiment.csv"
MASTER_CSV   = FINAL_DIR   / "hotel_daily_master.csv"


def main():
    if not REVIEWS_CSV.exists():
        print("ERROR: outputs/reviews_with_sentiment.csv not found.")
        print("       Run scripts/15_analyze_reviews_nlp.py first.")
        sys.exit(1)

    reviews = pd.read_csv(REVIEWS_CSV)
    if "date" not in reviews.columns or "sentiment" not in reviews.columns:
        print("ERROR: reviews file missing 'date' or 'sentiment' columns.")
        sys.exit(1)

    reviews["date"] = pd.to_datetime(reviews["date"], errors="coerce")
    reviews = reviews.dropna(subset=["date"])
    if reviews.empty:
        print("No dated reviews available — cannot create time-series features.")
        print("Tip: ensure your review export includes a date/publish_time column.")
        sys.exit(0)

    print(f"Loaded {len(reviews)} dated reviews "
          f"({reviews['date'].min().date()} – {reviews['date'].max().date()})")

    # Daily sentiment aggregates
    daily = (
        reviews.groupby(reviews["date"].dt.normalize())
               .agg(sentiment_mean=("sentiment", "mean"),
                    review_count=("sentiment", "count"),
                    has_negative=("sentiment", lambda x: int((x < -0.1).any())))
               .reset_index()
               .rename(columns={"date": "business_date"})
    )

    master = pd.read_csv(MASTER_CSV, parse_dates=["business_date"])
    master = master.sort_values("business_date").reset_index(drop=True)

    # Merge daily signals, then rolling 30-day window
    merged = master.merge(daily, on="business_date", how="left")
    merged["sentiment_mean"]  = merged["sentiment_mean"].fillna(np.nan)
    merged["review_count"]    = merged["review_count"].fillna(0)
    merged["has_negative"]    = merged["has_negative"].fillna(0)

    merged["review_sentiment_30d"] = (
        merged["sentiment_mean"]
              .rolling(30, min_periods=1)
              .mean()
    )
    merged["review_volume_30d"] = (
        merged["review_count"]
              .rolling(30, min_periods=1)
              .sum()
    )
    merged["complaint_flag"] = (
        merged["has_negative"]
              .rolling(30, min_periods=1)
              .max()
              .astype(int)
    )

    # Drop intermediates
    merged = merged.drop(columns=["sentiment_mean", "review_count", "has_negative"])

    merged.to_csv(MASTER_CSV, index=False)
    print(f"Updated master dataset with review features → {MASTER_CSV.relative_to(BASE_DIR)}")

    # Summary
    non_null = merged["review_sentiment_30d"].notna().sum()
    print(f"  Rows with sentiment coverage: {non_null} / {len(merged)}")
    print(f"  Mean 30d sentiment: {merged['review_sentiment_30d'].mean():.3f}")
    print(f"  Days with complaint flag: {int(merged['complaint_flag'].sum())}")
    print("\nDone. Re-run script 11 (train_model.py) to incorporate review features.")


if __name__ == "__main__":
    main()
